### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by SkyCrunchy007** [paperboi/kindle2notion#16]
Not sure what went wrong here

Code:

Traceback (most recent call last):
  File "/Users/denise/Kindle2Notion/kindle2notion.py", line 151, in <module>
    cv = client.get_collection_view(NOTION_TABLE_ID)
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 165, in get_collection_view
    collection = self.get_block(
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 118, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 111, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "/usr/local/lib/python3.9/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "/usr/local/lib/python3.9/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 209, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.

**Comment by paperboi** [comment]
Um, could you tell me what you did so I can retrace your steps and see?

**Comment by lhrinaldi** [comment]
@SkyCrunchy007 @paperboi hey this HTTPError seems similar to the one I had. Have a try at #14, and see if you can fix the problem.

**Comment by paperboi** [comment]
@SkyCrunchy007 check it out and let me know if it works out for ya. Cheers!
