### ISSUE TITLE
[HELP] Unable to connect with Notion 

### ISSUE THREAD

**Issue by acter-khan** [paperboi/kindle2notion#17]
When I try to run the script, it gives me the following error:

_Traceback (most recent call last):
  File "kindle2notion.py", line 9, in <module>
    from settings import CLIPPINGS_FILE, NOTION_TOKEN, NOTION_TABLE_ID, ENABLE_HIGHLIGHT_DATE
  File "F:\k2n\settings.py", line 5, in <module>
    CLIPPINGS_FILE = config('CLIPPINGS_FILE')
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: CLIPPINGS_FILE not found. Declare it as envvar or define a default value._ 

I believe it is due to something I am not doing correctly when creating the .env file. I am a beginner so I don't know what I am doing wrong.

Content of k2n.env file:
CLIPPINGS_FILE = "‪F:\k2n\My Clippings.txt"
NOTION_TOKEN = "7fed1060c5efc2d9a08329935c2e99c85ae834df0c86cbab1aec3aeb69c00f890e2ec4e17971c4824ddad240842151d2e753c5ca58faa68859d3776ba1d71b1e88aa9d8d702e9ff984940*******"
NOTION_TABLE_ID = "https://www.notion.so/zainkhan/1d7805cf81014931b77aa36c83cd6618?v=354a8fe2452a4b13b766a7843*******"
ENABLE_HIGHLIGHT_DATE = True

Looking forward to the help and thank you in advance.

**Comment by paperboi** [comment]
Is the file name of your .env file "k2n.env"? If so, rename it to just ".env"

**Comment by acter-khan** [comment]
That worked, changing the name to '.env' has resolved the issue.

However, it is now giving the following error:
```

Traceback (most recent call last):
  File "kindle2notion.py", line 9, in <module>
    from settings import CLIPPINGS_FILE, NOTION_TOKEN, NOTION_TABLE_ID, ENABLE_HIGHLIGHT_DATE
  File "F:\k2n\settings.py", line 5, in <module>
    CLIPPINGS_FILE = config('CLIPPINGS_FILE')
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 197, in __call__
    self._load(self.search_path or self._caller_path())
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 187, in _load
    self.config = Config(Repository(filename, encoding=self.encoding))
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\site-packages\decouple.py", line 124, in __init__
    for line in file_:
  File "C:\Users\Technolet\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
