### ISSUE TITLE
No module named 'regex._regex'

### ISSUE THREAD

**Issue by meitantenik** [paperboi/kindle2notion#28]
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/main/.local/lib/python3.9/site-packages/kindle2notion/__main__.py", line 4, in <module>
    from kindle2notion.exporting import export_to_notion
  File "/home/main/.local/lib/python3.9/site-packages/kindle2notion/exporting.py", line 4, in <module>
    from dateparser import parse
  File "/home/main/.local/lib/python3.9/site-packages/dateparser/__init__.py", line 3, in <module>
    from .date import DateDataParser
  File "/home/main/.local/lib/python3.9/site-packages/dateparser/date.py", line 6, in <module>
    import regex as re
  File "/usr/lib/python3/dist-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/usr/lib/python3/dist-packages/regex/regex.py", line 402, in <module>
    import regex._regex_core as _regex_core
  File "/usr/lib/python3/dist-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

**Comment by paperboi** [comment]
Seems like your system doesn't have regex package installed. Try running `pip install regex` or refer to this [link](https://nomodulenamed.com/m/regex.regex).

**Comment by meitantenik** [comment]
Requirement already satisfied

**Comment by meitantenik** [comment]
I think the problem is with wheel on Linux
