### ISSUE TITLE
401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent

### ISSUE THREAD

**Issue by pablokv** [paperboi/kindle2notion#59]
Hi, I am trying again (yesterday was working) and I face issues with the HTTP Client. I also tried logging in and out from Notion and getting a new token, but the issue is still there.

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kindle2notion\__main__.py", line 49, in <module>
    main()
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kindle2notion\__main__.py", line 31, in main
    notion_client = NotionClient(token_v2=notion_token)
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\client.py", line 95, in __init__
    self._update_user_info()
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\client.py", line 126, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\client.py", line 265, in post
    response.raise_for_status()
  File "C:\Users\pfern\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent**
```

**Comment by pablokv** [comment]
@paperboi do you know about this issue?

**Comment by aghasy** [comment]
Had the same issue, my tokenv2 has expired. I had fixed it by updating it!

Hope this could help

**Comment by hainguyen-namiq** [comment]
I have the same issue. I get a new tokenv2. But it till not work

**Comment by conceptrice26** [comment]
getting the same error, it's not fixed by updating token, url ,or double checking document location

**Comment by enriqueiturriagaa** [comment]
any updates?

**Comment by zhangbingxyx112** [comment]
any update for this issues, I had the same issues..

**Comment by loganylchen** [comment]
Hi All,

I think you must have used integration token instead of token_v2, which you can only get from the logon browser.

**Comment by paperboi** [comment]
Hi, just got around to addressing this in the latest version of the package. Like @loganylchen mentioned, you may have mixed up the official Notion API's integration token with the token_v2 id used for this package. The current update uses a different method and uses the Notion API for sending/retrieving details. Request you to take a look at the README and docs for the same. Sorry for the long absence, had a lot going on in my life that I couldn't make time for this sooner.
