### ISSUE TITLE
Error Handling Preventing Script Termination

### ISSUE THREAD

**Issue by niallCDS** [paperboi/kindle2notion#6]
```Traceback (most recent call last):
  File "/Applications/kindle2notion/kindle2notion.py", line 200, in <module>
    ch = KindleClippings(CLIPPINGS_FILE)
  File "/Applications/kindle2notion/kindle2notion.py", line 13, in __init__
    self.clippings = self._getAllClippings(clippingsFile)
  File "/Applications/kindle2notion/kindle2notion.py", line 18, in _getAllClippings
    return self._parseClippings(allClippings)
  File "/Applications/kindle2notion/kindle2notion.py", line 96, in _parseClippings
    self.addToNotion(lastClip)
  File "/Applications/kindle2notion/kindle2notion.py", line 185, in addToNotion
    title = "Page: " + lastClip['Page'] + "\tDate Added: " +  str(lastClip['Date Added'].strftime("%A, %d %B %Y %I:%M:%S %p"))
TypeError: can only concatenate str (not "NoneType") to str
```

Need error handling for such errors to prevent termination of script

**Comment by paperboi** [comment]
Hi, this has been resolved in the latest commit. Retooled the program to prevent this error from happening and speed up the loading process.
