### ISSUE TITLE
HTTPError( requests.exceptions.HTTPError: Invalid input.) - Even after changing the limit to 100

### ISSUE THREAD

**Issue by theneo13** [paperboi/kindle2notion#63]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kindle2notion\__main__.py", line 49, in <module>
    main()
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kindle2notion\__main__.py", line 38, in main
    export_to_notion(
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kindle2notion\exporting.py", line 35, in export_to_notion
    message = _add_book_to_notion(
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kindle2notion\exporting.py", line 87, in _add_book_to_notion
    notion_collection_view_rows = notion_collection_view.collection.get_rows()
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\collection.py", line 239, in get_rows
    return self.query(**kwargs)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\collection.py", line 236, in query
    return CollectionQuery(self, self._get_a_collection_view(), **kwargs).execute()
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\collection.py", line 385, in execute
    self._client.query_collection(
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\client.py", line 294, in query_collection
    return self._store.call_query_collection(*args, **kwargs)
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\store.py", line 344, in call_query_collection
    response = self._client.post("queryCollection", data).json()
  File "C:\Users\hello\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notion\client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.

I used this without any error but recently installed SSD in my machine with a fresh install of windows. And installed python just to use this amazing script, but getting this error. I followed the solution and changed the limit to 100, but it isn't working anymore.

**Comment by ttuan** [comment]
@theneo13 I have the same problem. Fixed it with this command:

`pip install git+https://github.com/jamalex/notion-py.git@refs/pull/352/merge`

and rerun `python -m kindle2notion 'notion_token' 'notion_table_id' 'clipping_file_path'`

Reference: https://github.com/jamalex/notion-py/pull/352#issuecomment-937553265

**Comment by cleswell** [comment]
does anyone have any updates on this? Tried every trick in the book...

**Comment by paperboi** [comment]
Hi, it took forever to find a solution (and find time to implement it) but please update the package on your local system and refer to the docs on how to run it. I essentially had to move to another Notion Python wrapper that's makes API calls through the official Notion API.
