### ISSUE TITLE
"from more_itertools import grouper" needs to commented on the packages.

### ISSUE THREAD

**Issue by lertsoft** [paperboi/kindle2notion#78]
Really small issue and easy to solve as it is correct right now on GitHub.
This line of code on exporting.py needs to be commented
```
from more_itertools import grouper # Not good

# from more_itertools import grouper #Good

```
Again this is fixed on the repo but not on the packages.

I found this by downloading the package from pip and kept getting this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/kindle2notion", line 33, in <module>
    sys.exit(load_entry_point('kindle2notion==1.0.0', 'console_scripts', 'kindle2notion')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/kindle2notion", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kindle2notion/__main__.py", line 5, in <module>
    from kindle2notion.exporting import export_to_notion
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kindle2notion/exporting.py", line 11, in <module>
    from more_itertools import grouper
ModuleNotFoundError: No module named 'more_itertools'
```

Raising this issue in case someone else's finds it and it's wondering wtf is happening.

**Comment by paperboi** [comment]
Wow, this must have flown past my radar before uploading. Thanks for reporting this.
The latest version of the package can be found [here](https://pypi.org/project/kindle2notion/1.0.1/).
