### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by ygaitonde** [paperboi/kindle2notion#88]
**Describe the bug**
I'm running the script in the normal fashion: `kindle2notion INTEGRATION_KEY DATABASE_ID FILE_LOC`.

**To Reproduce**
`kindle2notion INTEGRATION_KEY DATABASE_ID FILE_LOC`.

**Expected behaviour**
The program uploads my clippings to Notion.

**Screenshots**
```
Initiating transfer...

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/kindle2notion", line 33, in <module>
    sys.exit(load_entry_point('kindle2notion==1.0.1', 'console_scripts', 'kindle2notion')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kindle2notion/__main__.py", line 44, in main
    export_to_notion(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kindle2notion/exporting.py", line 36, in export_to_notion
    message = _add_book_to_notion(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/kindle2notion/exporting.py", line 97, in _add_book_to_notion
    notion.databases.query(notion_database_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/notional/session.py", line 356, in query
    if issubclass(target, ConnectedPage):
TypeError: issubclass() arg 1 must be a class
```

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
[Here's a link to my clippings.](https://gist.github.com/ygaitonde/94f288361f416412e77b8aa44ffd4a61)

**Comment by tobiasfamos** [comment]
I have the same error. Also on MacOS, on a Kindle Oasis, Firmware Version 5.15.1

**Comment by Mahaprasad003** [comment]
Same error. Any fix yet?
