### ISSUE TITLE
Error when trying to export.

### ISSUE THREAD

**Issue by Bergene** [paperboi/kindle2notion#90]
**Describe the bug**
I get an error when trying to export my clippings to Notion. 

**To Reproduce**
Steps to reproduce the behaviour:
I just ran the program with the specified parameters. I have followed the instructions. 

**Expected behaviour**
To be able to export clippings to Notion

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 109.0.5414.75

**Additional context**

Error message: 

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\kindle2notion\__main__.py", line 63, in <module>
    main()
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\kindle2notion\__main__.py", line 32, in main
    db = notion.databases.retrieve(notion_database_id)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\notional\session.py", line 291, in retrieve
    dbid = DatabaseRef[dbref].database_id
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\notional\core.py", line 91, in __getitem__
    return compose_func(params)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\notional\types.py", line 81, in __compose__
    ref = ObjectReference[db_ref]
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\notional\core.py", line 91, in __getitem__
    return compose_func(params)
  File "C:\Users\kbergene\AppData\Roaming\Python\Python310\site-packages\notional\types.py", line 40, in __compose__
    return ObjectReference(id=ref)
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ObjectReference
id
  value is not a valid uuid (type=type_error.uuid)

**Comment by Bergene** [comment]
Fixed this by removing the single quotes from the command. 
Initially I had just copied the example and removed the content inside the double quotes. After removing the quotes themselves it worked..

**Comment by Mahaprasad003** [comment]
Hey Bergene.
I am running the script but get the following error:

Error: Got unexpected extra argument (Clippings.txt')

Could you pls verify if am writing the syntax correct?

Command:

kindle2notion 'secret_xxxx' '2018xxx' 'E:\documents\My Clippings.txt'

**Comment by Bergene** [comment]
Hi Mahaprasad.

I don't think this is the same issue as me but I can try to help. 

The command I now run each time looks like this: 
`python -m kindle2notion secret_xxxx 2018xxx "E:\documents\My Clippings.txt"`
as this does not work for me: 
`python -m kindle2notion 'secret_xxxx ' '2018xxx ' '"F:\documents\My Clippings.txt"'`

I believe the issue you are experiencing is caused due to the script thinking that your path to the 'My Clippings' file are two arguments despite the quotes encompassing it. 

Try to run the command as I do, no quotes for the first two arguments and only quotes for the path to your clippings file.

**Comment by Mahaprasad003** [comment]
Hey Bergene. Thanks a lot for responding.

I do not know why, but it still doesn't work for me. I contacted the creator of the tool and he said that there's an issue with the underlying package the code is written on.

The chrome extension mentioned [here](https://github.com/paperboi/kindle2notion/discussions/53) did the work for me. I think I'll continue using it.

Appreciate the response 😇
