### ISSUE TITLE
Unsure if My input format is correct: 401 Client Error

### ISSUE THREAD

**Issue by cwrighta7xx** [paperboi/kindle2notion#93]
**Describe the bug**
I keep getting a 401 Client Error when I run the code. I double check that my Notion Internal Integration Token is update, notion database ID is correct, I reset cache on my web browser, logged in and out of notion, but I still get the following error:

C:\Users\Caleb>kindle2notion "secret_Eh3g2e177gW6SU74Xi9zpYxOolkWbIBKZZsE2bTExuL" "cf7fef4ee2ab4e1e8a517f894e5f0377" "C:\Users\Caleb\Desktop\Reading_Notes\My Clippings.txt"
Traceback (most recent call last):
  File "c:\users\caleb\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\caleb\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Caleb\Anaconda3\Scripts\kindle2notion.exe\__main__.py", line 9, in <module>
  File "c:\users\caleb\anaconda3\lib\site-packages\click\core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\caleb\anaconda3\lib\site-packages\click\core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "c:\users\caleb\anaconda3\lib\site-packages\click\core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\caleb\anaconda3\lib\site-packages\click\core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\caleb\anaconda3\lib\site-packages\kindle2notion\__main__.py", line 19, in main
    notion_client = NotionClient(token_v2=notion_token)
  File "c:\users\caleb\anaconda3\lib\site-packages\notion\client.py", line 76, in __init__
    self._update_user_info()
  File "c:\users\caleb\anaconda3\lib\site-packages\notion\client.py", line 82, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
  File "c:\users\caleb\anaconda3\lib\site-packages\notion\client.py", line 214, in post
    response.raise_for_status()
  File "c:\users\caleb\anaconda3\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.notion.so/api/v3/loadUserContent

Is there anything in my inputs that looks off?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox

**Comment by HL03** [comment]
Same here. Any solutions?
